apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: statusquarkusio-fjtw
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-gljb-tenant/status-quarkus-io/statusquarkusio-fjtw@sha256:f041b20e027f16a4b5dc0dcbe389165349628a7f2be4ec096231bb8c8c4c320f
        name: my-java-quarkus
        resources: {}
status: {}
